name: horses
channels:
  - conda-forge
  - defaults
  - microsoft

dependencies:
  - python=3.8
  - pip
  - pip:
    - pymongo[srv]
    - scrapy
    - scrapy-playwright
    - py3-validate-email
    - requests
    - playwright